project:
  type: book
  output-dir: docs
  resources:
    - static/**

book:
  title: "Informe SatOri"
  author: 
    - name: Abel Herrera
      email: mauricio.herrera@umayor.cl
      affiliations:
        - name: Hemera Centro de Observación de la Tierra, UMayor
    - name: Manuel Muñoz
      email: munozrodriguez.manuel@gmail.com
      affiliations: 
        - name: Ministerio del Medio Ambiente, Chile.
    - name: Francisco Zambrano
      orcid: 0000-0001-6896-8534
      email: francisco.zambrano@umayor.cl
      affiliations:
        - name: Hemera Centro de Observación de la Tierra, UMayor
  date: today
  page-footer:
    left: |
      SatOri | Proyecto FONDE IDEA I+Di ID21I10297.
    right: |
      Este informe fue creado con <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  site-url: https://s4tori.cl/informe
  repo-url: https://github.com/FONDEF-ID21-10297/informe
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - 001_prefacio.qmd
    - 002_intro.qmd
    - part: 'Metodología'
      chapters:
        - 101_area_estudio.qmd
        - 102_parametros_fisiologicos.qmd
        - 103_parametros_produccion.qmd
        - 104_modelo_potencial.qmd
        - 105_plataforma.qmd
    - part: 'Resultados'
      chapters:
        - 201_fisiologia.qmd
        - 202_produccion.qmd
        - 203_potencial.qmd
        - 204_satori.qmd
    - references.qmd

bibliography: references.bib

filters:
  - lightbox

format:
  html:
    toc: true
    toc-depth: 4
    toc_expand: false
    theme: cosmo
    mermaid: 
        theme: neutral
  pdf:
    documentclass: scrreprt

engine: knitr

execute:
  echo: false
  warning: false
  message: false

lang: es

editor: visual